from django.db import models
import random
# Create your models here.
class Contact_form(models.Model):
    user = models.CharField(max_length=20,default=str(random.randint(10,1000))+"user_fake")
    paid_up_capital_1 = models.IntegerField()
    Reserves_Funds = models.IntegerField()
    Reserve_Fund_2 = models.IntegerField()
    Other_Reserves_2 = models.IntegerField()
    Share_Premium_Accounts_2 = models.IntegerField()
    Deposits_3 = models.IntegerField()
    Current_Deposits_3 = models.IntegerField()
    From_Banks1 = models.IntegerField()
    From_Others = models.IntegerField()
    Savings_Deposits = models.IntegerField()
    Fixed_Deposits_33 = models.IntegerField()
    From_Banks331 = models.IntegerField()
    From_Others332 = models.IntegerField()
    Savings_Deposits32 = models.IntegerField()
    Borrowings_4 = models.IntegerField()
    Borrowings_from_Banks_in_India_4 = models.IntegerField()
    Reserve_Bank_of_India_4 = models.IntegerField()
    State_Bank_of_India_4 = models.IntegerField()
    Associates_of_the_State_Bank_of_India_4 = models.IntegerField()
    Other_Commercial_Bank_4 = models.IntegerField()
    Co_operative_Banks4 = models.IntegerField()
    Borrowings_from_Banks_outside_India4 = models.IntegerField()
    Borrowings_from_financial_institution_in_india4 = models.IntegerField()
    IDBI_SIDBI4 = models.IntegerField()
    National_Bank_for_Agriculture_Rural_Development4 = models.IntegerField()
    Export_Import_Bank_of_India4 = models.IntegerField()
    Other_Financial_Institutions_NHB4 = models.IntegerField()
    Borrowings_from_Financial_Institution_outside_India4 = models.IntegerField()
    Other_Liabilities5 = models.IntegerField()
    Bills_payable_in_India5 = models.IntegerField()
    Drawn_by_Indian_Offices5 = models.IntegerField()
    Drawn_by_Foreign5 = models.IntegerField()
    Bills_payable_outside_India_5 = models.IntegerField()
    Calls_received_in_advance_5 = models.IntegerField()
    Miscellaneous_liabilities_5 = models.IntegerField()
    Branch_Adjustments_6 = models.IntegerField()
    Among_offices_in_India_6 = models.IntegerField()
    With_offices_outside_6 = models.IntegerField()
    Total_Demand_Time_7 = models.IntegerField()
    Balance_of_profit_8 = models.IntegerField()
    Balance_of_profit_1 = models.IntegerField()
    Balance_of_profit_2 = models.IntegerField()
    Balance_of_profit_3 = models.IntegerField()
    Balance_of_profit_4 = models.IntegerField()
    Balance_of_profit_5 = models.IntegerField()
    Total_Liabilities = models.IntegerField()
    Cash_in_hand = models.IntegerField()
    Balances_with_the_Reserve_Bank_of_India = models.IntegerField()
    Balances_with_other_Banks_in_India_in_Current_Account = models.IntegerField()
    SBI31 = models.IntegerField()
    Associates_of_the_State_Bank_of_India = models.IntegerField()
    Other_Commercial_Banks = models.IntegerField()
    Co_operative_Banks34 = models.IntegerField()
    Money_at_call_Short_Notice = models.IntegerField()
    With_Commerical_Banks = models.IntegerField()
    With_Co_operative_Banks = models.IntegerField()
    With_Other_Financial_Institutions = models.IntegerField()
    Investments = models.IntegerField()
    Treasury_Bills = models.IntegerField()
    Other_Central_Government_Securites = models.IntegerField()
    State_Government_Securities = models.IntegerField()
    Other_approved_securities = models.IntegerField()
    Shares_debentures_of_companies = models.IntegerField()
    Fixed_Deposits_with_Banks = models.IntegerField()
    Other_Investments_in_India = models.IntegerField()
    Bills_purchased = models.IntegerField()
    Inland_bills_purchased = models.IntegerField()
    Foreign_Bills_purchased = models.IntegerField()
    Export_bills_drawn_in_India = models.IntegerField()
    Import_Bills_drawn_on_payable_in_India = models.IntegerField()
    Other_Foreign_bills_purchase_discounted = models.IntegerField()
    Payable_in_India = models.IntegerField()
    Payable_outside_India = models.IntegerField()
    Loans_Advances = models.IntegerField()
    Loans_advances_cash_credis_overdrafts = models.IntegerField()
    Due_from_banks = models.IntegerField()
    Co_operative_banks_in_India = models.IntegerField()
    Commercial_Banks_in_India = models.IntegerField()
    Banks_Outside_India = models.IntegerField()
    Premised = models.IntegerField()
    Branch_adjustments = models.IntegerField()
    Among_offices_in_India = models.IntegerField()
    With_offices_outside_India = models.IntegerField()
    Capitalised = models.IntegerField()
    Non_banking = models.IntegerField()
    Other_tangible_assets = models.IntegerField()
    Total_Assets = models.IntegerField()

    def __str__(self):
        return self.user


# class LIABILITIES_IN_INDIA(models.Model):
#     paid_up_capital = models.CharField(max_length=30,blank=True, null=True)
#     Reserve_Fund = models.CharField(max_length=30,default="hi",blank=True)
#     Other_Reserves = models.CharField(max_length=30,default="hi",blank=True)
#     Share_Premium_Accounts = models.CharField(max_length=30,default="hi",blank=True)
#     def __str__(self):
#         return self.Reserve_Fund
#     Bills_payable_in_India5 = models.IntegerField()